version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3.8.3-management
    container_name: celery_rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_VHOST=admin
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./data/rabbitmq3:/var/lib/rabbitmq3
  mysql:
    image: mysql:5.7
    container_name: celery_mysql
    restart: always
    privileged: true
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=081502
    volumes:
      - "./data/mysql/my.cnf:/etc/mysql/my.cnf"
      - "./data/mysql/data:/var/lib/mysql"
      - "./data/mysql/init/:/docker-entrypoint-initdb.d/"
    command: ['--character-set-server=utf8', '--collation-server=utf8_general_ci']


