version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3.8.3-management
    container_name: celery_rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_VHOST=admin
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./data/rabbitmq3:/var/lib/rabbitmq3
